import localFont from "next/font/local";
import "./globals.css";
import { CookiesProvider } from "next-client-cookies/server";
import { UserProvider } from "./context/UserContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "oAuth 2.0",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body><CookiesProvider><UserProvider>{children}</UserProvider></CookiesProvider></body>
    </html>
  );
}
